moved user group description annotation - was causing test failure
21:55:42 [admin] Created group prod/subscriptions/users
21:55:42 error: undefined method `resource' for nil:NilClass